name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'  # Ignore version tags like v1.0.0
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Run tests
        run: mvn test

      - name: List target contents
        run: ls -lh target

      - name: Archive JAR file
        run: mv target/genart-0.0.1-SNAPSHOT.jar .

      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: genart-0.0.1-SNAPSHOT.jar
          path: genart-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: List target contents
        run: pwd

      - name: Download JAR file artifact
        uses: actions/download-artifact@v4
        with:
          name: genart-0.0.1-SNAPSHOT.jar

      - name: List target contents
        run: ls -lh genart-0.0.1-SNAPSHOT.jar

      - name: Copy JAR file to AWS EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: genart.jar
          target: /home/${{ secrets.AWS_USERNAME }}/artgen/genart.jar

      - name: Run application on AWS EC2
        uses: actions/checkout@v4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            pkill -f "genart.jar" || true
            nohup java -jar /home/${{ secrets.AWS_USERNAME }}/artgen/genart-*.jar > app.log 2>&1 &