name: Release Build

on:
  push:
    tags:
      - 'v*'  # Triggers only when pushing a version tag, e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Run tests
        run: mvn test

      # Create GitHub Release and Upload Artifact
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT}}
